Přidání getBankAccounts
fakturoid/fakturoid-php pull request #26
Opened 2022-03-21 16:21 UTC by TakeruDavis

Přidání metody na stažení seznamu bankovních účtů, viz. #25

2022-03-24 13:29 UTC, goodhoko requested changes
@TakeruDavis Moc děkujeme za PR! Vypadá to dobře. Jen jedna  drobnost níže a taky zbývá přidat odpovídající test do https://github.com/fakturoid/fakturoid-php/blob/main/tests/Fakturoid/ClientTest.php

Pak to můžeme mergnout a releasnout. 👍

2022-03-25 19:57 UTC, TakeruDavis commented on lib/Fakturoid/Client.php
> +        return $this->get('/bank_accounts.json', $this->filterOptions($params, array('page')), $headers);
Děkuji za připomínku, také v účtu na kterém testujeme nemáme dostatek účtů na stránkování.

Trochu mne tu zmátla dokumentace. Vycházel jsem z metody getUsers, v [dokumentaci na Apiary](https://fakturoid.docs.apiary.io/#reference/users/users-collection/seznam-uzivatelu-k-uctu) tato metoda také měla uvedený pouze `slug`, ale v PHP kódu měla parametr `page` povolen, tak jsem se přiklonil k tvrzení z https://fakturoid.docs.apiary.io/#introduction/strankovani

2022-03-25 20:10 UTC, TakeruDavis commented
Přidání do ClientTest.php bude muset ještě počkat na příští, nemám teď možnost otestovat. Pak to sem přidám, ať to můžeme mergnout najednou

2022-03-25 20:17 UTC, TakeruDavis commented
Tak on to sem Github stejně přidal. Ale nemám odzkoušeno jestli ten test funguje

2022-03-28 08:43 UTC, goodhoko commented on lib/Fakturoid/Client.php
> +        return $this->get('/bank_accounts.json', $this->filterOptions($params, array('page')), $headers);
> ycházel jsem z metody getUsers, v [dokumentaci na Apiary](https://fakturoid.docs.apiary.io/#reference/users/users-collection/seznam-uzivatelu-k-uctu) tato metoda také měla uvedený pouze slug, ale v PHP kódu měla parametr page povolen

Máte pravdu, tady máme zastaralou dokumentaci. 🙈 To si opravíme, moc díky za upozornění!

Endpoint 'bank_accounts' paginaci vskutku neumí.

2022-03-28 08:50 UTC, goodhoko commented
> Tak on to sem Github stejně přidal. Ale nemám odzkoušeno jestli ten test funguje

Otestováno lokálně - vše OK. Ještě jednou díky za pomoc. .)

2022-03-28 08:50 UTC, goodhoko approved these changes

2022-03-28 08:51 UTC, merged

2022-03-28 09:57 UTC, goodhoko commented on lib/Fakturoid/Client.php
> +        return $this->get('/bank_accounts.json', $this->filterOptions($params, array('page')), $headers);
Dokumentace [opravena](https://github.com/fakturoid/api/commit/b0108b8d3a58b5abb31738d39d49dddc4974ed78). (Už je to i online na Apiary.)

2022-03-28 11:56 UTC, goodhoko commented
@TakeruDavis právě jsme releasnuli novou verzi s tvými změnam. 😉 https://packagist.org/packages/fakturoid/fakturoid-php